
# To find latest tags: 
# https://hub.docker.com/r/sonatype/nexus3

name: nexus

volumes:
  nexus-data: {}

services:

  # Main Nexus service
  nexus:
    image: sonatype/nexus3:3.53.1
    volumes:
      - type: volume
        source: nexus-data
        target: /nexus-data
        read_only: false
    ports:
      - target: 8081
        published: 8182
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost:8081/"]
      interval: 10s
      timeout: 2s
      retries: 30 # Can take time to start up first time
    stop_grace_period: 120s
    depends_on:
      nginx:
        condition: service_started
    restart: unless-stopped

  # nginx service to act as a remote Helm repo (for demonstration purposes)
  nginx:
    image: library/nginx:1.23.3-alpine
    ports:
      - target: 80
        published: 18185
    healthcheck:
      test: ["CMD", "curl", "-kf", "http://localhost:80/"]
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - type: bind
        source: ${PWD}/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ${PWD}/nginx/html
        target: /usr/share/nginx/html
        read_only: true
    restart: unless-stopped

  # Init container to setup Nexus
  nexus-init:
    image: byrnedo/alpine-curl:latest
    volumes:
      - type: bind
        source: ${PWD}/nexus-config
        target: /config
        read_only: true
      # Mount Nexus data volume to get initial password
      - type: volume
        source: nexus-data
        target: /nexus-data
        read_only: true
    environment:
      - NEXUS_DATA_DIR=/nexus-data
      - NEXUS_BASE_URL=http://nexus:8081
      - NEXUS_PASSWORD=MyAdminPassword
      - CONFIG_ROOT_DIR=/config
    entrypoint: "/bin/sh"
    command:  [ "/config/scripts/init.sh" ]
    depends_on:
      nexus:
        condition: service_healthy
    restart: on-failure:1
  


